### ISSUE TITLE
Unknown command "CHECK DTRACE"

### ISSUE THREAD

**Issue by Winters123** [rbruenig/qperf#1]
Hi, 

First, thanks for sharing this useful tool. But when I `cmake` the project, it terminated with an error `unknown command "CHECK DTRACE"`. Then I checked the `extern` directory and the cmake file of `quicly`. I found that `picotls` which is a dependee that `quicly` need is not installed.

Then I used `git submodule init/update` to download the `picotls` and re`cmake` the project in `build-qperf` directory. However, there was an `IOError` occurred. How should I proceed? :) 
![image](https://user-images.githubusercontent.com/16469534/68384966-b2fa9700-0150-11ea-8bcb-10939aea3523.png)

Thanks and regards,
Xiangrui

**Comment by rbruenig** [comment]
The quicly submodule again has submodules as dependencies. I'm guessing you ran `git submodule update --init` without the `--recursive` flag. Please run `git submodule update --init --recursive` or clone the repository with `--recurse-submodules` as described in the readme.

If during build you encounter the error `ev.h` missing please install the libev development packages (`libev-dev` on Ubuntu).

**Comment by Winters123** [comment]
thanks. youre right. I missed `picotls` because the missed `--recursive`. Problem solved.
