### ISSUE TITLE
failed to load certificate:server.crt:No such file or directory

### ISSUE THREAD

**Issue by h2cw2l** [rbruenig/qperf#11]
![image](https://user-images.githubusercontent.com/58133919/117773830-5effcf80-b26b-11eb-8cd8-d10ce93cb9cf.png)

How to solve this ?

Any reply will be appreciated.

**Comment by davidfdzp** [comment]
I solved it this way:
~/build-qperf$ openssl genrsa -des3 -out server.key 1024
Enter something as password, e.g. 0000

Then: ~/build-qperf$ openssl req -new -key server.key -out server.csr
Enter required data.

~/build-qperf$ openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
Enter required data.

Source: https://www.thegeekstuff.com/2009/07/Linux-Apache-mod-ssl-generate-key-csr-crt-file/

**Comment by rbruenig** [comment]
Hi, sorry for the late reply. I see this is already closed, but for future reference (will also add this to readme).

You can create the needed TLS files with the following one-liner:
```
openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -sha256 -days 365 -nodes -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=www.example.com"
```
