### ISSUE TITLE
Assertion failed when connecting to localhost

### ISSUE THREAD

**Issue by davidfdzp** [rbruenig/qperf#14]
~/build-qperf$ ./qperf -c localhost
starting client with host localhost, port 18080, runtime 10s, cc reno, iw 10
connection establishment time: 9ms
time to first byte: 9ms
qperf: ~/qperf/extern/quicly/lib/quicly.c:4146: do_send: Assertion `min_packets_to_send <= s->max_datagrams' failed.
Aborted (core dumped)

**Comment by davidfdzp** [comment]
I upgraded WSL from Ubuntu 18.04 to Ubuntu 20.04, cmake and make again and now it works. 
./qperf -c localhost
starting client with host localhost, port 18080, runtime 10s, cc reno, iw 10
connection establishment time: 7ms
time to first byte: 7ms
second 0: 144.4 mbit/s (18920319 bytes received)
second 1: 117.8 mbit/s (15439449 bytes received)
second 2: 121.4 mbit/s (15915828 bytes received)
second 3: 112.3 mbit/s (14717836 bytes received)
second 4: 122.5 mbit/s (16050571 bytes received)
second 5: 118.6 mbit/s (15546839 bytes received)
second 6: 122.3 mbit/s (16033068 bytes received)
second 7: 120.9 mbit/s (15846801 bytes received)
second 8: 123.2 mbit/s (16143517 bytes received)
second 9: 123.1 mbit/s (16130884 bytes received)
connection closed

**Comment by davidfdzp** [comment]
I am afraid I have to open this again. I am getting it again after pulling the latest version (git pull) then doing the git submodule update --recursive, cmake and make as indicated in the README.

**Comment by davidfdzp** [comment]
It is an issue of quicly: https://github.com/h2o/quicly/issues/516

**Comment by rbruenig** [comment]
Thanks for updating this issue. I will monitor the linked ticket and update qperf once and update in quicly is available
